Repository 2025-PinTech-Hackathon/Team03-BE, pull requests merged in 2025-05, with the labels that each got.

#8 ♻️ Refactor/#7 ENUM 타입 수정, 추가
  src/main/java/com/example/fintech/domain/account/entity/Account.java
  src/main/java/com/example/fintech/domain/allowanceSchedule/entity/AllowanceSchedule.java
  src/main/java/com/example/fintech/domain/quest/converter/QuestConverter.java
  src/main/java/com/example/fintech/domain/quest/entity/Category.java
  src/main/java/com/example/fintech/domain/quest/entity/Quest.java
  src/main/java/com/example/fintech/domain/quest/entity/Status.java
  src/main/java/com/example/fintech/domain/spendingConstraint/entity/Type.java
  src/main/java/com/example/fintech/domain/user/entity/SocialType.java
  src/main/java/com/example/fintech/domain/user/entity/User.java
Labels: ♻️ Refactor

#12 ♻️ Refactor/#9 transation 테이블 수정
  src/main/java/com/example/fintech/domain/transaction/entity/Transaction.java
  src/main/java/com/example/fintech/domain/user/entity/User.java
Labels: ♻️ Refactor

#10 ✨ Feat/#6 퀘스트 삭제
  src/main/java/com/example/fintech/domain/quest/controller/QuestController.java
  src/main/java/com/example/fintech/domain/quest/exception/QuestErrorCode.java
  src/main/java/com/example/fintech/domain/quest/service/QuestService.java
  src/main/java/com/example/fintech/domain/quest/service/QuestServiceImpl.java
Labels: ✨ Feat

#19 ✨ Feat/#11 퀘스트 종료, 완료
  src/main/java/com/example/fintech/domain/account/repository/AccountRepository.java
  src/main/java/com/example/fintech/domain/merchantCategory/repository/MerchantCategoryRepository.java
  src/main/java/com/example/fintech/domain/quest/controller/QuestController.java
  src/main/java/com/example/fintech/domain/quest/exception/QuestErrorCode.java
  src/main/java/com/example/fintech/domain/quest/service/QuestService.java
  src/main/java/com/example/fintech/domain/quest/service/QuestServiceImpl.java
  src/main/java/com/example/fintech/domain/transaction/entity/Transaction.java
  src/main/java/com/example/fintech/domain/transaction/repository/TransactionRepository.java
Labels: ✨ Feat

#28 Chore/#23 CORS PATCH 추가
  src/main/java/com/example/fintech/global/config/WebConfig.java
Labels: 📦 Chore

#40 ✨ Feat/#38 소비 페이지 api
  src/main/java/com/example/fintech/domain/transaction/controller/TransactionController.java
  src/main/java/com/example/fintech/domain/transaction/converter/HistoryConverter.java
  src/main/java/com/example/fintech/domain/transaction/dto/request/MonthlyReportRequestDTO.java
  src/main/java/com/example/fintech/domain/transaction/dto/response/HistoryResponse.java
  src/main/java/com/example/fintech/domain/transaction/dto/response/MonthlyReportResponseDTO.java
  src/main/java/com/example/fintech/domain/transaction/repository/TransactionRepository.java
  src/main/java/com/example/fintech/domain/transaction/service/HistoryService.java
  src/main/java/com/example/fintech/domain/transaction/service/HistoryServiceImpl.java
  src/main/java/com/example/fintech/domain/transaction/service/PaymentReportService.java
  src/main/java/com/example/fintech/domain/transaction/service/PaymentReportServiceImpl.java
Labels: ✨ Feat

#42 ♻️ Refactor/#41 오늘의 소비내역 한줄평 응답형식 변경
  src/main/java/com/example/fintech/domain/home/controller/HomeController.java
Labels: ♻️ Refactor

#46 ♻️ Refactor/#45 TransactionRequestConverter timestamp type 변경
  src/main/java/com/example/fintech/domain/trasactionRequest/Converter/TransactionRequestConverter.java
Labels: ♻️ Refactor
